[tool.poetry]
name = "docs"
version = "0.0.1"
description = ""
authors = ["The DAML Authors"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
sphinx-autobuild = "*"
sphinx = "*"
jinja2 = ">=2.10.1"
urllib3 = ">=1.24.2"
